#### リニアサーチ
##### 入力
    - 数列A = < A[1], A[2], A[3], ... A[n]>
    - 数列のサイズ n
    - 探す数 v
##### 出力
    Aの中に、vと等しい数がある場合、≪見つかる≫と出力する。<br>
    Aの中に、vと等しい数がない場合、≪見つからない≫と出力する。
##### 疑似コード
|行|実行回数|コード|
|---:|:---:|:---|
|L1:|1|procedure LINEAR-SEARCH(A,n,v)|
|L2:|1|&emsp;&emsp;k ← 1|
|L3:|M+1-S|&emsp;&emsp;while k ≦ n do|
|L4:|M|&emsp;&emsp;&emsp;&emsp;if A[k] = v then|
|L5:|S|&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;return ≪見つかる≫|
|L6:|0|&emsp;&emsp;&emsp;&emsp;end-if|
|L7:|M-S|&emsp;&emsp;&emsp;&emsp;k ← k + 1|
|L8:|M-S|&emsp;&emsp;end-while|
|L9:|1-S|&emsp;&emsp;return ≪見つからない≫|
|L10:|1|end-procedure|

- Sは成功フラグを表すindicator
- S = 1 は v が見つかる場合。M = v
- S = 0 は v が見つからない場合。M = n

リニアサーチの実行ステップ数は、<br>
**4M - 3S + 5**

In [ ]:
import random

def linearSearch(sequence,size,target):
    i = 0
    while i < size:
        if sequence[i] == target:
            return "見つかる"
        i += 1
    return "見つからない"

A = [31, 41, 59, 26, 53]
n = len(A)
v = 26

print(A)
print("searching " + str(v))
print(linearSearch(A,n,v))

stop = 10**100
listsize = 5*(10**5)
B = [random.randrange(0, stop , 1) for i in range(listsize)]
n = len(B)
v = random.randrange(0, stop, 1)

print(B[:10])
print("...")
print("searching " + str(v))
print(linearSearch(B,n,v))

### 番兵(sentinel)付きリニアサーチ

##### 疑似コード
|行|実行回数|コード|
|---:|:---:|:---|
|S1:|1|procedure SENTINEL-LINEAR-SEARCH(A,n,v)|
|S2|1|&emsp;&emsp;A[n + 1] ← v|
|S3:|1|&emsp;&emsp;k ← 1|
|S4:|M + 1 - S|&emsp;&emsp;while A[k] ≠ v do|
|S5|M - S|&emsp;&emsp;&emsp;&emsp;k ← k + 1|
|S6|M - S|&emsp;&emsp;end-while|
|S7:|1|&emsp;&emsp;if A[k] ≦ n then|
|S8:|S|&emsp;&emsp;&emsp;&emsp;return ≪見つかる≫|
|S9:|0|&emsp;&emsp;end-if|
|S10:|1-S|&emsp;&emsp;return ≪見つからない≫|
|S11:|1|end-procedure|

番兵付きリニアサーチの実行ステップ数は、<br>
**3M - 3S + 7**<br>

リニアサーチの実行ステップ数 - 番兵付きリニアサーチの実行ステップ数<br>
= (4M - 3S + 5) - (3M - 3S + 5)<br>
= M - 2<br>
**vが最初に見つかる位置が3番目以降なら、番兵付きリニアサーチはリニアサーチより約25%速い**

In [ ]:
import random

def linearSearch(sequence,size,target):
    sequence.append(target)
    i = 0
    while sequence[i] != target:
        i += 1
    if ( i + 1 ) <= size:
        return "見つかる"
    return "見つからない"

A = [31, 41, 59, 26, 53]
n = len(A)
v = 26

print(A)
print("searching " + str(v))
print(linearSearch(A,n,v))

stop = 10**100
listsize = 5*(10**5)
B = [random.randrange(0, stop , 1) for i in range(listsize)]
n = len(B)
v = random.randrange(0, stop, 1)

print(B[:5])
print("...")
print("searching " + str(v))
print(linearSearch(B,n,v))

### 指数的爆発
||ビットオーダー|
|---:|:---|
|地球を構成する原子の総数|$2^{170}$個|
|銀河系を構成する原子の総数|$2^{223}$個|
|全宇宙の体積|$2^{280}$㎤|

────"Applied Cryptography"より

In [10]:
import random

order= 16
number = 2 ** order
list = []
for i in range(number):
    list.append(random.randrange(0, number, 1))

print(list[:10])

[50579, 37705, 57670, 52324, 57616, 40761, 21067, 41080, 29389, 3448]


In [13]:
import random

order= 24
number = 2 ** order
list = []
for i in range(number):
    list.append(random.randrange(0, number, 1))

print(list[:10])

[7716049, 6822298, 13095147, 16179788, 6062753, 16409544, 12378190, 6645508, 2242346, 11101659]


### 確率の意味
- 公理的確率: ≪確率の公理≫によって定めた確率。
- 古典的確率: ≪場合の数の比≫によって定めた確率。同じ確からしさを持つ出来事とは何であるかを前もって決め、≪注目している場合の数≫÷≪すべての場合の数≫=≪場合の数の比≫で確率を表す。
- 統計的確率: ≪発生頻度の比≫によって定めた確率。

### 確率の公理（コルモゴロフによる）
Ωを集合とし、A, BをΩの部分集合とする。
PrをΩの部分集合から実数への関数とする。
関数Prが以下の公理P1, P2, P3を満たすとする。

公理 P1 0≦Pr(A)≦1
公理 P2 Pr(Ω)=1
公理 P3 A∩B={}ならば、Pr(A∪B)=Pr(A)+Pr(B)

このとき、
- 集合Ωを**標本空間**と呼び、
- Ωの部分集合を**事象**と呼び、
- 関数Prを**確率分布**と呼び、
- 実数Pr(A)をAが起きる**確率**と呼ぶ。

### 期待値
確率変数Xの期待値E[X]を次式で定義する。<br>
$E[X] = \sum_{k=0}^{\infty}c_k\cdot Pr(X=c_k)$
ここで<br>
- $X=[c_0, c_1, c_2, c_3 \ldots, c_k \ldots]$<br>
- $Pr(X=c_k)$は確率変数Xが$c_k$に等しくなる確率を表す。

### 期待値の線形性
- $E[X+Y]=E[X]+E[Y]$
- $E[K\cdot X]=K\cdot E[X] (ただしKは定数)$

一般的に
$X=X_1+X_2+X_3+\ldots+X_n$のとき、<br>
$E[X]=E[X_1]+E[X_2]+E[X_3]+\ldots+E[X_n]=\sum_{k=1}^{n}E[X_k]$<br>
また<br>
$E[X]=E[\sum_{k=1}^{n}X_k]$より<br>
$E[\sum_{k=1}^{n}X_k]=\sum_{k=1}^{n}E[X_k]$<br>
と書ける。

In [4]:
# 和の期待値と期待値の和が等しくなるかのシミュレーション

import random

sampleSize = 5 # 確率変数の数
factor = 2 # 確率変数が取りうる値の数
sampleList = [] # 確率変数と確率分布のセットをを入れる箱

def sampleMaker(sampleList, sampleSize, factor):
    for n in range(sampleSize):
        randomVariable = [random.randint(0,factor) for i in range(factor)] # 確率変数列
        probabilityDistribution = [] # 確率分布列

        # 確率分布生成
        pdSeed = [random.randint(1,factor) for i in range(factor)]
        total = sum(pdSeed)
        for i in range(len(pdSeed)):
            probabilityDistribution.append(pdSeed[i] / total)

        tuplelist = []
        for i in range(factor):
            tuplelist.append((randomVariable[i],probabilityDistribution[i]))

        sampleList.append(tuplelist)

sampleMaker(sampleList, sampleSize, factor)
'''リストの中のタプルの取り出し方
for l in sampleList:
    for t in l:
        print(t[0]*t[1])
'''

print(sampleList)

# 和の期待値
''' 未完成。和の期待値をコードで表現するのはややこしい
expectedValue1 = 0
tupleSeries = []
for l in range(factor):
    tupleSeries.append([])

print(sampleList[1][0])

for t in range(factor):
    for l in range(sampleSize):
        tupleSeries[t].append(sampleList[l][t])

print(tupleSeries)

'''

# 期待値の和
expectedValue2 = 0
suml =[]
for l in range(sampleSize):
    suml.append([])
    for t in sampleList[l]:
        suml[l].append(t[0]*t[1])

for i in range(len(suml)):
    expectedValue2 += sum(suml[i])

print(expectedValue2)

[[(2, 0.6666666666666666), (1, 0.3333333333333333)], [(1, 0.6666666666666666), (1, 0.3333333333333333)], [(2, 0.6666666666666666), (2, 0.3333333333333333)], [(2, 0.5), (0, 0.5)], [(1, 0.6666666666666666), (1, 0.3333333333333333)]]
(1, 0.6666666666666666)
[[(2, 0.6666666666666666), (1, 0.6666666666666666), (2, 0.6666666666666666), (2, 0.5), (1, 0.6666666666666666)], [(1, 0.3333333333333333), (1, 0.3333333333333333), (2, 0.3333333333333333), (0, 0.5), (1, 0.3333333333333333)]]
6.666666666666666


### 二項分布
##### **定義**
2つの母数$p(0≤p≤1), n（nは自然数）$に対して、$0$以上の<u>整数を値としてとる</u>確率変数$X$の確率質量関数が<br>
$P_n(k)=\dbinom{n}{k} p^k (1-p)^{n-k}$<br>
で与えられるとき、確率変数Xは母数$(n, p)$の二項分布$B(n, p)$に従うという。これを$X \sim B(n, p)$と表記する。

##### **解釈**
$n$回の試行で成功確率$p$の事象が$k$回起こるときの確率を意味する。<br>
ex.) 表が出る確率が$p$で、裏が出る確率が$(1-p)$のコインを$n$回投げたとき、表が$k$回出る確率$P_n(k)$

二項分布の期待値は<u>定義</u>と<u>二項定理</u>から証明ができる。<br>
https://mathlandscape.com/binomial-distrib-ev/

### $O$(オー)記法

#### **定義**
$\exists N \in \mathbb{N} \; \exists C ＞ 0 \; \forall n \geq N \; \left[|T(n)| \leq C n \right] $<br>
このとき<br>
≪関数$T(n)$は、たかだか$n$のオーダーである≫
という。
これを<br>
$T(n) = O(n)$<br>
と表す。<br><br>

Oの中のnは関数でもよい。すなわち、<br>
$\exists N \in \mathbb{N} \; \exists C ＞ 0 \; \forall n \geq N \; \left[|T(n)| \leq C f(n) \right] $<br>
このとき<br>
≪関数$T(n)$は、たかだか$f(n)$のオーダーである≫
という。
これを<br>
$T(n) = O(f(n))$<br>
と表す。

### $Ω$(オメガ)記法

#### **定義**

$\exists N \in \mathbb{N} \; \exists C ＞ 0 \; \forall n \geq N \; \left[|T(n)| \geq C f(n) \right] $<br>
このとき<br>
≪関数$T(n)$は、少なくとも$f(n)$のオーダーである≫
という。
これを<br>
$T(n) = Ω(f(n))$<br>
と表す。

### $Θ$(シータ)記法

#### **定義**

$\exists N \in \mathbb{N} \; \exists C_1 ＞ 0 \; C_2 ＞ 0 \; \forall n \geq N \; \left[C_2 f(n) \leq |T(n)| \leq C_1 f(n) \right] $<br>
このとき<br>
≪関数$T(n)$は、ちょうど$f(n)$のオーダーである≫
という。
これを<br>
$T(n) = Θ(f(n))$<br>
と表す。<br>
定義より、<br>
$T(n) = O(f(n))$ かつ $T(n) = Ω(f(n))$ ならば、<br>
$T(n) = Θ(f(n))$

### ガウスの消去法

行列を用いて連立一次方程式を解くアルゴリズム。<br>
ガウスの消去法を用いて簡単に**逆行列**や**行列式**（の値）を求められる。<br>
計算機に解かせることができるので、変数の値が非常に大きい場合に**逆行列**や**行列式**を求めるのに応用可能。<br>
<br>
**行列の基本変形**のみを用いて、前進消去にて上三角行列を作成し、後退代入によって変数の解を得る。<br>

#### 行列の基本変形
- 行倍: ある行を0でない定数倍（スカラー倍）する。
- 行和: ある行の0でない定数倍を他の行に加える。
- 行換: 2つの行を入れ替える。

行列の基本変形は連立一次方程式の意味を変えない変形なので、このアルゴリズムで連立一次方程式の解を得られるのは明らか。

##### 前進消去
行列の基本変形を用いて、**行階段形**を作る操作。<br>
<br>
次の性質を満たす行列を**行階段形**という。<br>
- ゼロでない成分を持つ行（少なくとも一つの成分がゼロでない行）が、ゼロしか成分に持たない行よりも上に位置している（ゼロ成分だけからなる行が存在するならば、それらは行列の最下部に配置される）。
- 主成分（行の最も左にあるゼロでない成分。かなめ、あるいはpivot）が、その行の上にある行の主成分よりも、真に右側に位置する。

cf. ある行列から作られる行階段形の行列は一意ではない（行階段形のスカラー倍も行階段形となる）。行階段形を進めた **既約行階段形（行簡約階段形）** は一意となる。

##### 後退代入
最下段の行から最後の変数の値を求め、それを順次上の行に代入していくことで他の変数の値を求める操作。<br>

In [6]:
'''実装例
https://watlab-blog.com/2020/05/01/gaussian-elimination/
より
'''
import numpy as np
 
def gaussian_elimination(A, b):
    try:
        n = len(b)
        # 前進消去を行う
        for i in range(n):
            # pivot選択機能---------------------------------------------------------------------------------
            order = np.argmax(np.abs(A[i:, i]))  # pivot列i行目以上で最も絶対値の高い行を検索
            temp_A = A[i + order].copy()         # Aについて、最も絶対値の高い行成分を抽出し、別メモリで一時保持する
            temp_b = b[i + order].copy()         # bについて、最も絶対値の高い行成分を抽出し、別メモリで一時保持する
            A[i + order] = A[i]                  # Aについて、一時保持した行にi行目成分を置換する
            A[i] = temp_A                        # Aについて、保持しておいた行をi行目に置換する
            b[i + order] = b[i]                  # bについて、一時保持した行にi行目成分を置換する
            b[i] = temp_b                        # bについて、保持しておいた行をi行目に置換する
            # ----------------------------------------------------------------------------------------------
            pivot = A[i, i]                      # 対角成分をpivotに代入
 
            # pivotが小さい時はエラーとする
            if np.abs(pivot) < 1e-6:
                print('pivot=', pivot)
                raise ZeroDivisionError
 
            A[i] = A[i] / pivot                  # pivotで係数行列を割り、A[i,i]を1にする
            b[i] = b[i] / pivot                  # 定数ベクトルもpivotで割り同値変形する
 
            # i行目の定数倍をi+1行目以降から引くループ
            for j in range(i+1, n):
                p = A[j, i]                      # i+1行目以降i列の数値を格納
                A[j] -= p * A[i]                 # 係数行列のi+1行目からi行目の定数倍を引く
                b[j] -= p * b[i]                 # 定数ベクトルのi+1行目からi行目の定数倍を引く
 
        # 後退代入を行う
        x = np.zeros(n)                          # 解の入れ物を用意
        for i in reversed(range(n)):             # 最終行から後退処理する
            x[i] = b[i] / A[i, i]                # 解を求める
            for j in range(i):
                b[j] -= A[j, i] * x[i]           # 解が求まった列分bの値を上から更新する
        print('Normal termination')
    except:
        print('Error termination : pivot too small.')
        x = np.nan
    return x
 
# 係数行列(n次正方行列であること)
A = np.array([
    [1, -1, -2, 2],
    [2, -1, -3, 3],
    [-1, 3, 3, -2],
    [1, 2, 0, -1]], dtype=float)
 
# 定数ベクトル
b = np.array([5, 10, 2, -10], dtype=float)
 
# ガウスの消去法関数を実行して解を得る
x = gaussian_elimination(A, b)
print(x)

Normal termination
[ 9. -4. 15. 11.]


In [33]:
'''上記実装例によるシミュレーション
'''
import numpy as np
import random

# パラメータ設定
n = 100 # 正方行列の次数
r = 1000 # 要素の値の範囲(0 <= value < r)

def gaussian_elimination(A, b): # ガウスの消去法を行う関数
    try:
        n = len(b)
        # 前進消去を行う
        for i in range(n):
            # pivot選択機能---------------------------------------------------------------------------------
            order = np.argmax(np.abs(A[i:, i]))  # pivot列i行目以上で最も絶対値の高い行を検索
            temp_A = A[i + order].copy()         # Aについて、最も絶対値の高い行成分を抽出し、別メモリで一時保持する
            temp_b = b[i + order].copy()         # bについて、最も絶対値の高い行成分を抽出し、別メモリで一時保持する
            A[i + order] = A[i]                  # Aについて、一時保持した行にi行目成分を置換する
            A[i] = temp_A                        # Aについて、保持しておいた行をi行目に置換する
            b[i + order] = b[i]                  # bについて、一時保持した行にi行目成分を置換する
            b[i] = temp_b                        # bについて、保持しておいた行をi行目に置換する
            # ----------------------------------------------------------------------------------------------
            pivot = A[i, i]                      # 対角成分をpivotに代入
 
            # pivotが小さい時はエラーとする
            if np.abs(pivot) < 1e-6:
                print('pivot=', pivot)
                raise ZeroDivisionError
 
            A[i] = A[i] / pivot                  # pivotで係数行列を割り、A[i,i]を1にする
            b[i] = b[i] / pivot                  # 定数ベクトルもpivotで割り同値変形する
 
            # i行目の定数倍をi+1行目以降から引くループ
            for j in range(i+1, n):
                p = A[j, i]                      # i+1行目以降i列の数値を格納
                A[j] -= p * A[i]                 # 係数行列のi+1行目からi行目の定数倍を引く
                b[j] -= p * b[i]                 # 定数ベクトルのi+1行目からi行目の定数倍を引く
 
        # 後退代入を行う
        x = np.zeros(n)                          # 解の入れ物を用意
        for i in reversed(range(n)):             # 最終行から後退処理する
            x[i] = b[i] / A[i, i]                # 解を求める
            for j in range(i):
                b[j] -= A[j, i] * x[i]           # 解が求まった列分bの値を上から更新する
        print('Normal termination')
    except:
        print('Error termination : pivot too small.')
        x = np.nan
    return x

def generate_coefficient_matrix(n,r): # 係数行列を生成する関数
    A = np.zeros((n,n))
    for i in range(n):
        for j in range(n):
            A[i][j] = random.randrange(r)
    return A

def generate_constant_vector(n, r): # 定数ベクトルを生成する関数
    b = np.zeros(n)
    for i in range(n):
        b[i] = random.randrange(r)
    return b

# 係数行列(n次正方行列であること)
A = generate_coefficient_matrix(n,r)

print(A)

# 定数ベクトル
b = generate_constant_vector(n,r)

print(b)
 
# ガウスの消去法関数を実行して解を得る
x = gaussian_elimination(A, b)
print(x)

[[411.  94. 733. ...  33. 429. 964.]
 [661. 677.  62. ... 985. 981.  69.]
 [ 40. 469. 354. ... 588. 754. 208.]
 ...
 [351.  94. 619. ... 807. 728. 936.]
 [439. 826. 383. ... 123. 404. 260.]
 [820.  39. 556. ... 870. 270. 541.]]
[410. 358.  93. 419. 601. 724. 100.   7.  35. 296. 986. 571. 812. 786.
 213. 764. 832. 193. 153. 703. 596. 598. 669.  45. 408. 464. 424. 647.
 891.  12. 976. 802. 661. 769. 357. 702. 917. 670. 537. 575. 286. 835.
 705. 443. 866. 479. 885.  20. 658.   1. 571. 872. 367.  14. 233. 180.
 149. 169. 853. 949. 557. 906. 265. 129. 538. 551. 323. 332. 615. 678.
 886. 546. 559. 978. 199. 952. 862. 499.  41.  34. 493. 212. 890. 158.
 209. 655. 799.   7. 903. 451. 136. 786.  98. 512. 344. 733. 600. 612.
 938. 874.]
Normal termination
[ 0.1776047  -0.61210779  1.01349626  1.08996912  1.17868122 -0.08141998
  0.49090113  0.64212066  2.35503038 -0.05331485 -0.02036355 -1.40902581
 -0.18437683 -2.8306412   0.305173    0.15594075  0.19314362 -1.31863216
 -0.39917097  0.07470814 